# Generated by Django 4.1.3 on 2023-01-26 09:50

import DS_GET_SCRAPED_DATA_APIs.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scrapped_URL_Table',
            fields=[
                ('base_url', models.TextField(primary_key=True, serialize=False)),
                ('url_rendered', models.BooleanField(blank=True, default=False, null=True)),
                ('last_scraped_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(blank=True, default='NA', null=True)),
                ('text', models.TextField(blank=True, default='NA', null=True)),
                ('html', models.TextField(blank=True, default='NA', null=True)),
                ('website_category', models.CharField(default='NA', max_length=50)),
                ('screenshot', models.ImageField(blank=True, default='NA', null=True, upload_to=DS_GET_SCRAPED_DATA_APIs.models.get_save_path)),
                ('full_screenshot', models.ImageField(blank=True, default='NA', null=True, upload_to=DS_GET_SCRAPED_DATA_APIs.models.get_save_path)),
                ('page_pdf', models.FileField(blank=True, default='NA', null=True, upload_to=DS_GET_SCRAPED_DATA_APIs.models.get_save_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', ''])])),
            ],
        ),
        migrations.CreateModel(
            name='html_Tag_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField(blank=True, default='NA', null=True)),
                ('tag_inner_text', models.TextField(blank=True, default='NA', null=True)),
                ('raw_tag', models.TextField(blank=True, default='NA', null=True)),
                ('scrapped_URL_Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.scrapped_url_table')),
            ],
            options={
                'unique_together': {('scrapped_URL_Table', 'tag_name', 'tag_inner_text')},
            },
        ),
        migrations.CreateModel(
            name='html_Tag_Arg_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg_name', models.TextField(blank=True, default='NA', null=True)),
                ('arg_value', models.TextField(blank=True, default='NA', null=True)),
                ('html_Tag_Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.html_tag_table')),
                ('scrapped_URL_Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.scrapped_url_table')),
            ],
            options={
                'unique_together': {('scrapped_URL_Table', 'html_Tag_Table', 'arg_name', 'arg_value')},
            },
        ),
    ]
