# Generated by Django 4.1.3 on 2023-01-26 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappedURL',
            fields=[
                ('base_url', models.TextField(primary_key=True, serialize=False)),
                ('last_scraped_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(blank=True, default=-1, null=True)),
                ('text', models.TextField(blank=True, default=-1, null=True)),
                ('html', models.TextField(blank=True, default=-1, null=True)),
                ('website_category', models.CharField(default=-1, max_length=50)),
                ('screenshot', models.ImageField(upload_to='DS_CORE/saved_data')),
                ('full_screenshot', models.ImageField(upload_to='DS_CORE/saved_data')),
                ('page_pdf', models.FileField(upload_to='DS_CORE/saved_data')),
            ],
        ),
        migrations.CreateModel(
            name='p_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=-1, null=True)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.scrappedurl')),
            ],
            options={
                'unique_together': {('base_url', 'text')},
            },
        ),
        migrations.CreateModel(
            name='img_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, default=-1, null=True)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.scrappedurl')),
            ],
            options={
                'unique_together': {('base_url', 'link')},
            },
        ),
        migrations.CreateModel(
            name='h6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=-1, null=True)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.scrappedurl')),
            ],
            options={
                'unique_together': {('base_url', 'text')},
            },
        ),
        migrations.CreateModel(
            name='h5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=-1, null=True)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.scrappedurl')),
            ],
            options={
                'unique_together': {('base_url', 'text')},
            },
        ),
        migrations.CreateModel(
            name='h4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=-1, null=True)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.scrappedurl')),
            ],
            options={
                'unique_together': {('base_url', 'text')},
            },
        ),
        migrations.CreateModel(
            name='h3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=-1, null=True)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.scrappedurl')),
            ],
            options={
                'unique_together': {('base_url', 'text')},
            },
        ),
        migrations.CreateModel(
            name='h2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=-1, null=True)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.scrappedurl')),
            ],
            options={
                'unique_together': {('base_url', 'text')},
            },
        ),
        migrations.CreateModel(
            name='h1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=-1, null=True)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.scrappedurl')),
            ],
            options={
                'unique_together': {('base_url', 'text')},
            },
        ),
        migrations.CreateModel(
            name='a_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, default=-1, null=True)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_GET_SCRAPED_DATA_APIs.scrappedurl')),
            ],
            options={
                'unique_together': {('base_url', 'link')},
            },
        ),
    ]
