# Generated by Django 4.1.3 on 2023-01-26 03:42

import DS_GET_SCRAPED_DATA_APIs.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DS_GET_SCRAPED_DATA_APIs', '0002_alter_scrappedurl_page_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappedurl',
            name='full_screenshot',
            field=models.ImageField(upload_to=DS_GET_SCRAPED_DATA_APIs.models.get_save_path),
        ),
        migrations.AlterField(
            model_name='scrappedurl',
            name='page_pdf',
            field=models.FileField(upload_to=DS_GET_SCRAPED_DATA_APIs.models.get_save_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='scrappedurl',
            name='screenshot',
            field=models.ImageField(upload_to=DS_GET_SCRAPED_DATA_APIs.models.get_save_path),
        ),
    ]
