# Generated by Django 4.1.5 on 2023-03-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scrapped_URL_Table',
            fields=[
                ('base_url', models.TextField(primary_key=True, serialize=False)),
                ('url_rendered', models.BooleanField(blank=True, default=False, null=True)),
                ('last_scraped_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(blank=True, default='NA', null=True)),
                ('text', models.TextField(blank=True, default='NA', null=True)),
                ('html', models.TextField(blank=True, default='NA', null=True)),
                ('website_category', models.CharField(default='NA', max_length=50)),
                ('screenshot', models.BinaryField(blank=True, default=b'NA', editable=True, null=True)),
                ('full_screenshot', models.BinaryField(blank=True, default=b'NA', editable=True, null=True)),
                ('page_pdf', models.BinaryField(blank=True, default=b'NA', editable=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='crawl_URL_Table',
            fields=[
                ('base_url', models.TextField(primary_key=True, serialize=False)),
                ('parent_url', models.TextField(blank=True, default='NA', null=True)),
                ('seed_url', models.TextField(blank=True, default='NA', null=True)),
                ('last_crawled_time', models.DateTimeField(auto_now_add=True)),
                ('crawl_depth', models.IntegerField(blank=True, default=-1, null=True)),
                ('scrapped_URL_Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DS_CORE.scrapped_url_table')),
            ],
        ),
    ]
